exclude: '^tests/'

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black                 # Format Python code
        args: [--line-length=88]

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8               # Check code style/errors
        args: [--max-line-length=88, --ignore=E203]

  - repo: https://github.com/pycqa/autoflake
    rev: v2.1.1
    hooks:
      - id: autoflake             # Remove unused imports and variables
        args: [--in-place, --remove-all-unused-imports, --remove-unused-variables]
